insert into crime values(1,'bribery','imprisonment and/or fine double the value','','');
insert into crime values(2,'assault','imprisonment and/or fine','','');
insert into crime values(3,'cyber crime','community service order and/or imprisonment','','');
insert into crime values(4,'burglary','imprisonment','','');
insert into crime values(5,'drug possession','imprisonment and/or community service order and rehabilitation','','');
insert into crime values(6,'sexual assaults','imprisonment and community servie order','','');
insert into crime values(7,'robbery','imprisonment','','');
insert into crime values(8,'perjury','imprisonment and fine','','');
insert into crime values(9,'disturbing the peace','community service order and/or jail','','');
insert into crime values(10,'child abuse','imprisonment and community service order','','');
insert into crime values(11,'theft','imprisonment and/or fine','','');
insert into crime values(12,'extortion','imprisonment','','');
insert into crime values(13,'fraud','imprisonment and fine and community service order','','');
insert into crime values(14,'kidnapping','imprisonment','','');
insert into crime values(15,'solicitation','imprisonment','','');
insert into crime values(16,'arson','imprisonment and fine and/or community service order','','');
insert into crime values(17,'conspiracy','imprisonment and/or fine','','');
insert into crime values(18,'embezzlement','forfeiture of offenders property and/or fine','','');
insert into crime values(19,'harassment','imprisonment and community service order','','');
insert into crime values(20,'murder','execution or lifetime imprisonment and/or fine','','');
