INSERT INTO criminal_info (criminal_info_ssn,criminal_info_name,criminal_info_dob,criminal_info_age,criminal_info_sex,criminal_info_nationality,criminal_info_current_address,criminal_info_contact_no,criminal_info_remarks) VALUES (ai_criminal_info.NEXTVAL,'Chinmay Terse','14-Aug-1995',null,'m','Indian','Mumbai, India',9969983949,'Awesomeness Personified');

INSERT INTO criminal_info (criminal_info_ssn,criminal_info_name,criminal_info_dob,criminal_info_age,criminal_info_sex,criminal_info_nationality,criminal_info_current_address,criminal_info_contact_no,criminal_info_remarks) VALUES (ai_criminal_info.NEXTVAL,'Rahul Agarwal','10-Sep-1994',null,'m','Indian','Mumbai, India',9969669040,'Businessman');

INSERT INTO criminal_info (criminal_info_ssn,criminal_info_name,criminal_info_dob,criminal_info_age,criminal_info_sex,criminal_info_nationality,criminal_info_current_address,criminal_info_contact_no,criminal_info_remarks) VALUES (ai_criminal_info.NEXTVAL,'Pratik Kshirsagar','30-Sep-1995',null,'m','Indian','Mumbai, India',9820770430,'Extreme Gamer');

INSERT INTO criminal_info (criminal_info_ssn,criminal_info_name,criminal_info_dob,criminal_info_age,criminal_info_sex,criminal_info_nationality,criminal_info_current_address,criminal_info_contact_no,criminal_info_remarks) VALUES (ai_criminal_info.NEXTVAL,'Shreya Joshi','14-Aug-1995',null,'f','Indian','Mumbai, India',9833450158,'Indian Idol winner. NOT A MAHARASHTRIAN! Khatarnaak Joker');

INSERT INTO criminal_info (criminal_info_ssn,criminal_info_name,criminal_info_dob,criminal_info_age,criminal_info_sex,criminal_info_nationality,criminal_info_current_address,criminal_info_contact_no,criminal_info_remarks) VALUES (ai_criminal_info.NEXTVAL,'Rachana Ramesh','14-Aug-1995',null,'f','Indian','Mumbai, India',8879421779,'Vidya Maams favourite student, Coz andugunguthandapaani');

INSERT INTO criminal_info (criminal_info_ssn,criminal_info_name,criminal_info_dob,criminal_info_age,criminal_info_sex,criminal_info_nationality,criminal_info_current_address,criminal_info_contact_no,criminal_info_remarks) VALUES (ai_criminal_info.NEXTVAL,'Pradnyesh Baikar','14-Aug-1995',null,'m','Indian','Mumbai, India',9102035652,'CEO of GarmaGaram.com. Print guy. Also acts as a stand. Not a Biker');

INSERT INTO criminal_info (criminal_info_ssn,criminal_info_name,criminal_info_dob,criminal_info_age,criminal_info_sex,criminal_info_nationality,criminal_info_current_address,criminal_info_contact_no,criminal_info_remarks) VALUES (ai_criminal_info.NEXTVAL,'Shafqat Ali Barkat Ali Haji Ali Khan','14-Aug-1995',null,'m','Indian','Mumbai, India',9920880602,'HAR. ROZ. CHICKEN. Freaking Awesome man!');

INSERT INTO criminal_info (criminal_info_ssn,criminal_info_name,criminal_info_dob,criminal_info_age,criminal_info_sex,criminal_info_nationality,criminal_info_current_address,criminal_info_contact_no,criminal_info_remarks) VALUES (ai_criminal_info.NEXTVAL,'Abhishek Tiwari','14-Aug-1995',null,'m','Indian','Mumbai, India',9860667630,'OHU. But knows Mumbai better than most Mumbaikars. Potential Army candidate. Known only as Tiwari, wont respond to Abhishek.');

INSERT INTO criminal_info (criminal_info_ssn,criminal_info_name,criminal_info_dob,criminal_info_age,criminal_info_sex,criminal_info_nationality,criminal_info_current_address,criminal_info_contact_no,criminal_info_remarks) VALUES (ai_criminal_info.NEXTVAL,'Yogesh Kolhatkar','14-Aug-1995',null,'m','Indian','Mumbai, India',8793376923,'From Malkapur. Always talking crap. Give him a tapli whenever spotted.');
