insert into crime values(ai_crime.NEXTVAL,'bribery','imprisonment and/or fine double the value','','');
insert into crime values(ai_crime.NEXTVAL,'assault','imprisonment and/or fine','','');
insert into crime values(ai_crime.NEXTVAL,'cyber crime','community service order and/or imprisonment','','');
insert into crime values(ai_crime.NEXTVAL,'burglary','imprisonment','','');
insert into crime values(ai_crime.NEXTVAL,'drug possession','imprisonment and/or community service order and rehabilitation','','');
insert into crime values(ai_crime.NEXTVAL,'sexual assaults','imprisonment and community servie order','','');
insert into crime values(ai_crime.NEXTVAL,'robbery','imprisonment','','');
insert into crime values(ai_crime.NEXTVAL,'perjury','imprisonment and fine','','');
insert into crime values(ai_crime.NEXTVAL,'disturbing the peace','community service order and/or jail','','');
insert into crime values(ai_crime.NEXTVAL,'child abuse','imprisonment and community service order','','');
insert into crime values(ai_crime.NEXTVAL,'theft','imprisonment and/or fine','','');
insert into crime values(ai_crime.NEXTVAL,'extortion','imprisonment','','');
insert into crime values(ai_crime.NEXTVAL,'fraud','imprisonment and fine and community service order','','');
insert into crime values(ai_crime.NEXTVAL,'kidnapping','imprisonment','','');
insert into crime values(ai_crime.NEXTVAL,'solicitation','imprisonment','','');
insert into crime values(ai_crime.NEXTVAL,'arson','imprisonment and fine and/or community service order','','');
insert into crime values(ai_crime.NEXTVAL,'conspiracy','imprisonment and/or fine','','');
insert into crime values(ai_crime.NEXTVAL,'embezzlement','forfeiture of offenders property and/or fine','','');
insert into crime values(ai_crime.NEXTVAL,'harassment','imprisonment and community service order','','');
insert into crime values(ai_crime.NEXTVAL,'murder','execution or lifetime imprisonment and/or fine','','');
