insert into pen values(ai_pen.NEXTVAL,'Blackgate','New York, New York','Lewis Gordon',2000,5,1316);
insert into pen values(ai_pen.NEXTVAL,'Alcatraz','San Francisco, California','Benjamin Buttonn',1500,5,1201);
insert into pen values(ai_pen.NEXTVAL,'Walnuts','Las Vegas, Nevada','Ronnie Screwvala',5500,3,3001);
insert into pen values(ai_pen.NEXTVAL,'Redlight','Atlanta, Georgia','Barrak Pompala',4600,3,2007);
insert into pen values(ai_pen.NEXTVAL,'Angel Wings','Honolulu, Hawaii','Raul Sanchez',4200,4,2890);
insert into pen values(ai_pen.NEXTVAL,'Sunset Hills','Chicago, Illinois','James Brooke',1200,2,810);
insert into pen values(ai_pen.NEXTVAL,'Dawnbreak Heights','Orlando, Florida','Jay Zee',1250,2,675);
insert into pen values(ai_pen.NEXTVAL,'Braveheart Asylum','Anchorage, Alaska','Darius Noxiac',450,1,75);
insert into pen values(ai_pen.NEXTVAL,'Steelpunk Retreat','Tucson, Arizona','Yuvraj Agrawal',250,1,175);
insert into pen values(ai_pen.NEXTVAL,'Bittersweet Gates','New Jersey, New Jersey','Chunkey Pandey',350,1,205);
