insert into penitentiary values(1,'Blackgate','New York, New York','Lewis Gordon',2000,5,1316);
insert into penitentiary values(2,'Alcatraz','San Francisco, California','Benjamin Buttonn',1500,5,1201);
insert into penitentiary values(3,'Walnuts','Las Vegas, Nevada','Ronnie Screwvala',5500,3,3001);
insert into penitentiary values(4,'Redlight','Atlanta, Georgia','Barrak Pompala',4600,3,2007);
insert into penitentiary values(5,'Angel Wings','Honolulu, Hawaii','Raul Sanchez',4200,4,2890);
insert into penitentiary values(6,'Sunset Hills','Chicago, Illinois','James Brooke',1200,2,810);
insert into penitentiary values(7,'Dawnbreak Heights','Orlando, Florida','Jay Zee',1250,2,675);
insert into penitentiary values(8,'Braveheart Asylum','Anchorage, Alaska','Darius Noxiac',450,1,75);
insert into penitentiary values(9,'Steelpunk Retreat','Tucson, Arizona','Yuvraj Agrawal',250,1,175);
insert into penitentiary values(10,'Bittersweet Gates','New Jersey, New Jersey','Chunkey Pandey',350,1,205);
