insert into precinct values(1,'Tommy Hilfiger','Langley, Virginia',198,34);
insert into precinct values(2,'Toby Maguire','Boston, Massachussets',154,27);
insert into precinct values(3,'Anna Karenina','Long Island, New York',116,30);
insert into precinct values(4,'Daniel Craig','London, England',144,29);
insert into precinct values(5,'Diana Kruger','Los Angeles, California',84,20);
insert into precinct values(6,'Roger Smith','Miama, Florida',106,28);
insert into precinct values(7,'Kevin Peitersen','Atlanta, Georgia',100,31);
insert into precinct values(8,'Ellen DeGenres','New York, New York',156,38);
insert into precinct values(9,'Conrad Sewell','Cincinnati, Ohio',99,29);
insert into precinct values(10,'Daniel Radcliffe','Phoenix, Arizona',79,22);
insert into precinct values(11,'Ashley Tisdale','Pittsburgh, Pennsylvania',88,24);
insert into precinct values(12,'Doug Perry','Salt Lake City, Utah',98,29)
insert into precinct values(13,'Angelina Valentine','New Jersey, New Jersey',198,37);
insert into precinct values(14,'Dolan Trumb','Washington DC, Virginia',148,35);
insert into precinct values(15,'Pearce Ronin','New Orleans, Lousiana',100,40);
insert into precinct values(16,'Tyler Samson','Portland, Oregon',120,42);
insert into precinct values(17,'Phucdat Beach','Trollsburgh, Nevada',79,22);
insert into precinct values(18,'Rek Sai','The Void, Freelos',55,3);
insert into precinct values(19,'Johnny Boons','Dallas, Texas',27,7);
insert into precinct values(20,'Ronald McDonald','Kansas City, Kansas',47,9);
