insert into precinct values(ai_precinct.NEXTVAL,'Tommy Hilfiger','Langley, Virginia',198,34);
insert into precinct values(ai_precinct.NEXTVAL,'Toby Maguire','Boston, Massachussets',154,27);
insert into precinct values(ai_precinct.NEXTVAL,'Anna Karenina','Long Island, New York',116,30);
insert into precinct values(ai_precinct.NEXTVAL,'Daniel Craig','London, England',144,29);
insert into precinct values(ai_precinct.NEXTVAL,'Diana Kruger','Los Angeles, California',84,20);
insert into precinct values(ai_precinct.NEXTVAL,'Roger Smith','Miama, Florida',106,28);
insert into precinct values(ai_precinct.NEXTVAL,'Kevin Peitersen','Atlanta, Georgia',100,31);
insert into precinct values(ai_precinct.NEXTVAL,'Ellen DeGenres','New York, New York',156,38);
insert into precinct values(ai_precinct.NEXTVAL,'Conrad Sewell','Cincinnati, Ohio',99,29);
insert into precinct values(ai_precinct.NEXTVAL,'Daniel Radcliffe','Phoenix, Arizona',79,22);
insert into precinct values(ai_precinct.NEXTVAL,'Ashley Tisdale','Pittsburgh, Pennsylvania',88,24);
insert into precinct values(ai_precinct.NEXTVAL,'Doug Perry','Salt Lake City, Utah',98,29);
insert into precinct values(ai_precinct.NEXTVAL,'Angelina Valentine','New Jersey, New Jersey',198,37);
insert into precinct values(ai_precinct.NEXTVAL,'Dolan Trumb','Washington DC, Virginia',148,35);
insert into precinct values(ai_precinct.NEXTVAL,'Pearce Ronin','New Orleans, Lousiana',100,40);
insert into precinct values(ai_precinct.NEXTVAL,'Tyler Samson','Portland, Oregon',120,42);
insert into precinct values(ai_precinct.NEXTVAL,'Phucdat Beach','Trollsburgh, Nevada',79,22);
insert into precinct values(ai_precinct.NEXTVAL,'Rek Sai','The Void, Freelos',55,3);
insert into precinct values(ai_precinct.NEXTVAL,'Johnny Boons','Dallas, Texas',27,7);
insert into precinct values(ai_precinct.NEXTVAL,'Ronald McDonald','Kansas City, Kansas',47,9);
